version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: bits_brac
      MONGO_INITDB_ROOT_PASSWORD: biTSBraC
    ports:
      - 27017:27017
    volumes:
      - /opt/mongodb/data:/data/db

volumes:
  mongodb_data_container: