version: "3.9"

services:
  mysql:
    image: mysql:5.6
    container_name: mysql56
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: database
      MYSQL_USER: sazzad_1027
      MYSQL_PASSWORD: sample
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
