services:
  node-exporter:
    image: prom/node-exporter
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9211:9100"
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge
